version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: bank-transactions-container
    environment:
      POSTGRES_DB: bank-transactions-database
      POSTGRES_USER: bank-transactions-user
      POSTGRES_PASSWORD: bank-transactions-password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
